use crate::config::{AliasValue, ShellConfig};
use anyhow::{Context, Result};
use std::path::Path;

/// Generate all shell configuration files from the config
pub fn generate_all(cfg: &ShellConfig, output: &Path) -> Result<()> {
    let zshenv = generate_zshenv(cfg);
    let zshrc = generate_zshrc(cfg);
    let starship_toml = generate_starship(cfg);
    let skim_theme = generate_skim_theme(cfg);

    std::fs::write(output.join("zshenv"), &zshenv)
        .context("failed to write zshenv")?;
    std::fs::write(output.join("zshrc"), &zshrc)
        .context("failed to write zshrc")?;
    std::fs::write(output.join("starship.toml"), &starship_toml)
        .context("failed to write starship.toml")?;
    std::fs::write(output.join("skim_theme.sh"), &skim_theme)
        .context("failed to write skim_theme.sh")?;

    Ok(())
}

fn generate_zshenv(cfg: &ShellConfig) -> String {
    let mut out = String::new();
    out.push_str("# Generated by bm-shell-engine — do not edit\n\n");

    out.push_str("if [ -n \"$__BLACKMATTER_ZSHENV_SOURCED\" ]; then return; fi\n");
    out.push_str("export __BLACKMATTER_ZSHENV_SOURCED=1\n\n");

    // Nix daemon
    out.push_str("if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then\n");
    out.push_str("  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'\n");
    out.push_str("fi\n\n");

    // HM session vars
    out.push_str("# Load home-manager session variables\n");
    out.push_str("if [[ -f \"/etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh\" ]]; then\n");
    out.push_str("  source \"/etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh\"\n");
    out.push_str("elif [[ -f \"$HOME/.local/state/nix/profiles/home-manager/home-path/etc/profile.d/hm-session-vars.sh\" ]]; then\n");
    out.push_str("  source \"$HOME/.local/state/nix/profiles/home-manager/home-path/etc/profile.d/hm-session-vars.sh\"\n");
    out.push_str("elif [[ -f \"$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh\" ]]; then\n");
    out.push_str("  source \"$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh\"\n");
    out.push_str("fi\n\n");

    // Starship config
    if cfg.prompt.engine == "starship" {
        if let Some(ref path) = cfg.prompt.config_path {
            out.push_str(&format!("export STARSHIP_CONFIG=\"{path}\"\n"));
        }
    }

    // Ensure XDG dirs exist
    out.push_str("\nmkdir -p \"${XDG_STATE_HOME:-$HOME/.local/state}/zsh\"\n");
    out.push_str("mkdir -p \"${XDG_CACHE_HOME:-$HOME/.cache}/zsh\"\n");

    out
}

fn generate_zshrc(cfg: &ShellConfig) -> String {
    let mut out = String::new();
    out.push_str("# Generated by bm-shell-engine — do not edit\n\n");

    // Profiling
    out.push_str("[[ -n \"$ZPROF\" ]] && zmodload zsh/zprof\n\n");

    // Shell options
    out.push_str("# ===== SHELL OPTIONS =====\n");
    generate_shell_options(cfg, &mut out);
    out.push('\n');

    // History
    out.push_str("# ===== HISTORY =====\n");
    generate_history(cfg, &mut out);
    out.push('\n');

    // Theme colors as env vars
    out.push_str("# ===== THEME =====\n");
    for (name, color) in &cfg.theme.colors {
        let upper = name.to_uppercase();
        out.push_str(&format!("export {upper}=\"{color}\"\n"));
    }
    out.push_str("export CLICOLOR=1\n");
    out.push_str("export LS_COLORS=\"di=1;34:ln=36:so=32:pi=33:ex=1;32:bd=34;46:cd=34;43:su=1;31:sg=1;33:tw=34;42:ow=34;43:*.tar=31:*.tgz=31:*.zip=31:*.gz=31:*.bz2=31:*.7z=31:*.rar=31:*.xz=31:*.zst=31\"\n");
    out.push('\n');

    // Completion system
    out.push_str("# ===== COMPLETION =====\n");
    generate_completion(cfg, &mut out);
    out.push('\n');

    // Fuzzy finder setup
    out.push_str("# ===== FUZZY FINDER =====\n");
    generate_fuzzy(cfg, &mut out);
    out.push('\n');

    // Plugins sorted by priority
    out.push_str("# ===== PLUGINS =====\n");
    generate_plugins(cfg, &mut out);
    out.push('\n');

    // Keybindings
    out.push_str("# ===== KEYBINDINGS =====\n");
    generate_keybindings(cfg, &mut out);
    out.push('\n');

    // Widgets
    out.push_str("# ===== WIDGETS =====\n");
    generate_widgets(cfg, &mut out);
    out.push('\n');

    // Editor variables
    out.push_str("# ===== EDITOR =====\n");
    out.push_str("if command -v blnvim &> /dev/null; then\n");
    out.push_str("  export EDITOR='blnvim'\n  export VISUAL='blnvim'\n");
    out.push_str("else\n  export EDITOR='nvim'\n  export VISUAL='nvim'\nfi\n");
    out.push_str("export PAGER='less'\nexport LESS='-R -i -w -M -z-4 -x4'\nexport LESSHISTFILE='-'\n");
    out.push_str("export BAT_THEME=\"ansi\"\n");
    out.push_str("if command -v bat &> /dev/null; then\n");
    out.push_str("  export MANPAGER=\"sh -c 'col -bx | bat -l man -p'\"\n");
    out.push_str("  export MANROFFOPT='-c'\nfi\n\n");

    // Aliases
    out.push_str("# ===== ALIASES =====\n");
    generate_aliases(cfg, &mut out);
    out.push('\n');

    // Local overrides
    out.push_str("# ===== LOCAL OVERRIDES =====\n");
    out.push_str("for __bm_local in ~/.config/shell/local.d/*.zsh; do\n");
    out.push_str("  [[ -f \"$__bm_local\" ]] && source \"$__bm_local\"\n");
    out.push_str("done\nunset __bm_local\n\n");

    // Profiling end
    out.push_str("[[ -n \"$ZPROF\" ]] && zprof\n");

    out
}

fn generate_shell_options(cfg: &ShellConfig, out: &mut String) {
    let s = &cfg.shell;
    if s.auto_cd { out.push_str("setopt AUTO_CD AUTO_PUSHD PUSHD_IGNORE_DUPS PUSHD_MINUS\n"); }
    if s.extended_glob { out.push_str("setopt EXTENDED_GLOB GLOB_DOTS NO_CASE_GLOB NUMERIC_GLOB_SORT NO_NOMATCH\n"); }
    if s.interactive_comments { out.push_str("setopt INTERACTIVE_COMMENTS RC_QUOTES COMBINING_CHARS\n"); }
    out.push_str("setopt ALWAYS_TO_END AUTO_MENU AUTO_LIST COMPLETE_IN_WORD\n");
    out.push_str("unsetopt MENU_COMPLETE\n");
    out.push_str("setopt LONG_LIST_JOBS AUTO_RESUME NOTIFY\n");
    out.push_str("unsetopt BG_NICE HUP CHECK_JOBS\n");
    out.push_str("setopt NO_BEEP NO_FLOW_CONTROL\n");
    out.push_str(&format!("export FUNCNEST={}\n", s.func_nest));
    out.push_str(&format!("export KEYTIMEOUT={}\n", s.key_timeout));
    if s.vi_mode { out.push_str("bindkey -v\n"); }
}

fn generate_history(cfg: &ShellConfig, out: &mut String) {
    let h = &cfg.history;
    out.push_str(&format!("export HISTFILE=\"{}\"\n", h.file));
    out.push_str(&format!("[[ -d \"${{HISTFILE:h}}\" ]] || mkdir -p \"${{HISTFILE:h}}\"\n"));
    out.push_str(&format!("export HISTSIZE={}\nexport SAVEHIST={}\n", h.size, h.size));
    out.push_str("setopt EXTENDED_HISTORY INC_APPEND_HISTORY HIST_REDUCE_BLANKS HIST_VERIFY\n");
    if h.dedup { out.push_str("setopt HIST_EXPIRE_DUPS_FIRST HIST_IGNORE_ALL_DUPS HIST_FIND_NO_DUPS\n"); }
    if h.share { out.push_str("setopt SHARE_HISTORY\n"); }
    if h.ignore_space { out.push_str("setopt HIST_IGNORE_SPACE\n"); }
}

fn generate_completion(cfg: &ShellConfig, out: &mut String) {
    let c = &cfg.completion;
    out.push_str("local _zsh_cache=\"${XDG_CACHE_HOME:-$HOME/.cache}/zsh\"\n");
    out.push_str("[[ -d \"$_zsh_cache\" ]] || mkdir -p \"$_zsh_cache\"\n");
    out.push_str("autoload -Uz compinit\n");
    out.push_str(&format!("local zcompdump=\"$_zsh_cache/zcompdump-$HOST\"\n"));
    out.push_str(&format!("if [[ -n ${{zcompdump}}(#qN.mh+{}) ]] || [[ ! -f \"$zcompdump\" ]]; then\n", c.cache_hours));
    out.push_str("  compinit -d \"$zcompdump\"\nelse\n  compinit -C -d \"$zcompdump\"\nfi\n");
    out.push_str("{ [[ ! ${zcompdump}.zwc -nt ${zcompdump} ]] && zcompile \"${zcompdump}\" } &!\n\n");
    out.push_str("zstyle ':completion::complete:*' use-cache on\n");
    out.push_str("zstyle ':completion::complete:*' cache-path \"$_zsh_cache\"\n");
    out.push_str("zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'\n");
    out.push_str("zstyle ':completion:*:*:*:*:*' menu select\n");
    out.push_str("zstyle ':completion:*' list-colors \"${(s.:.)LS_COLORS}\"\n");
    out.push_str("zstyle ':completion:*' verbose yes\n");
    out.push_str("zstyle ':completion:*' group-name ''\n");
    out.push_str(&format!("zstyle -e ':completion:*:approximate:*' max-errors 'reply=($((($#PREFIX+$#SUFFIX)/3>7?7:($#PREFIX+$#SUFFIX)/3))numeric)'\n"));
    out.push_str("zstyle ':completion:*' rehash true\n");
    out.push_str("zstyle ':completion:*:cd:*' ignore-parents parent pwd\n");
    out.push_str("zstyle ':completion:*' special-dirs true\n");
    out.push_str("zstyle ':completion:*' accept-exact '*(N)'\n");
    out.push_str("zstyle ':completion:*' accept-exact-dirs true\n");
}

fn generate_fuzzy(cfg: &ShellConfig, out: &mut String) {
    let theme = &cfg.theme;
    let fg = theme.colors.get("nord4").map(|s| s.as_str()).unwrap_or("#D8DEE9");
    let bg = theme.colors.get("nord0").map(|s| s.as_str()).unwrap_or("#2E3440");
    let hl = theme.colors.get("nord8").map(|s| s.as_str()).unwrap_or("#88C0D0");
    let fg_sel = theme.colors.get("nord6").map(|s| s.as_str()).unwrap_or("#ECEFF4");
    let bg_sel = theme.colors.get("nord1").map(|s| s.as_str()).unwrap_or("#3B4252");
    let hl_sel = theme.colors.get("nord7").map(|s| s.as_str()).unwrap_or("#8FBCBB");
    let info = theme.colors.get("nord9").map(|s| s.as_str()).unwrap_or("#81A1C1");
    let prompt = theme.colors.get("nord14").map(|s| s.as_str()).unwrap_or("#A3BE8C");
    let pointer = theme.colors.get("nord11").map(|s| s.as_str()).unwrap_or("#BF616A");
    let marker = theme.colors.get("nord15").map(|s| s.as_str()).unwrap_or("#B48EAD");
    let header = theme.colors.get("nord10").map(|s| s.as_str()).unwrap_or("#5E81AC");
    let border = theme.colors.get("nord3").map(|s| s.as_str()).unwrap_or("#4C566A");
    let query = theme.colors.get("nord6").map(|s| s.as_str()).unwrap_or("#ECEFF4");

    let opts = format!(
        "--height 30% --layout=reverse --border=rounded --info=inline --ansi \
         --bind='ctrl-/:toggle-preview' --bind='ctrl-u:preview-half-page-up' --bind='ctrl-d:preview-half-page-down' \
         --preview-window='right:50%:hidden:wrap' \
         --color=fg:{fg},bg:{bg},hl:{hl} \
         --color=fg+:{fg_sel},bg+:{bg_sel},hl+:{hl_sel} \
         --color=info:{info},prompt:{prompt},pointer:{pointer} \
         --color=marker:{marker},spinner:{info},header:{header} \
         --color=border:{border},query:{query}"
    );

    if cfg.fuzzy.backend == "skim" {
        out.push_str(&format!("export SKIM_DEFAULT_OPTIONS=\"{opts}\"\n"));
        out.push_str("export FZF_DEFAULT_OPTS=\"$SKIM_DEFAULT_OPTIONS\"\n");
        out.push_str("if command -v fd &> /dev/null; then\n");
        out.push_str("  export SKIM_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --strip-cwd-prefix'\n");
        out.push_str("fi\n");
    } else {
        out.push_str(&format!("export FZF_DEFAULT_OPTS=\"{opts}\"\n"));
        out.push_str("if command -v fd &> /dev/null; then\n");
        out.push_str("  export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --strip-cwd-prefix'\n");
        out.push_str("fi\n");
    }
}

fn generate_plugins(cfg: &ShellConfig, out: &mut String) {
    let mut plugins: Vec<_> = cfg.plugins.iter().collect();
    plugins.sort_by_key(|(_, p)| p.priority);

    let (immediate, deferred): (Vec<_>, Vec<_>) = plugins.into_iter().partition(|(_, p)| !p.defer);

    for (name, plugin) in &immediate {
        if let Some(ref init) = plugin.init {
            out.push_str(&format!("# {name} (priority {})\n", plugin.priority));
            out.push_str(&format!("if command -v {name} &> /dev/null; then\n  {init}\nfi\n"));
        }
    }

    if !deferred.is_empty() {
        out.push_str("\n# Deferred plugins (loaded after first prompt)\n");
        out.push_str("__blackmatter_deferred() {\n");
        out.push_str("  add-zsh-hook -d precmd __blackmatter_deferred\n");
        out.push_str("  unfunction __blackmatter_deferred\n");
        for (name, plugin) in &deferred {
            if let Some(ref init) = plugin.init {
                out.push_str(&format!("  # {name}\n  {init}\n"));
            }
        }
        out.push_str("}\nautoload -Uz add-zsh-hook\nadd-zsh-hook precmd __blackmatter_deferred\n");
    }
}

fn generate_keybindings(cfg: &ShellConfig, out: &mut String) {
    // Required autoloads for search widgets
    out.push_str("autoload -Uz edit-command-line up-line-or-beginning-search down-line-or-beginning-search\n");
    out.push_str("zle -N edit-command-line\n");
    out.push_str("zle -N up-line-or-beginning-search\n");
    out.push_str("zle -N down-line-or-beginning-search\n\n");

    // Cursor shape changes for vi mode
    if cfg.shell.vi_mode {
        out.push_str("function zle-keymap-select {\n");
        out.push_str("  if [[ ${KEYMAP} == vicmd ]] || [[ $1 = 'block' ]]; then\n");
        out.push_str("    echo -ne '\\e[1 q'\n");
        out.push_str("  elif [[ ${KEYMAP} == main ]] || [[ ${KEYMAP} == viins ]] || [[ ${KEYMAP} = '' ]] || [[ $1 = 'beam' ]]; then\n");
        out.push_str("    echo -ne '\\e[5 q'\n");
        out.push_str("  fi\n}\nzle -N zle-keymap-select\n");
        out.push_str("echo -ne '\\e[5 q'\n");
        out.push_str("_blzsh_preexec() { echo -ne '\\e[5 q' }\nadd-zsh-hook preexec _blzsh_preexec\n\n");
    }

    for (mode, bindings) in &cfg.keybindings {
        for (key, action) in bindings {
            out.push_str(&format!("bindkey -M {mode} '{key}' {action}\n"));
        }
    }
}

fn generate_widgets(cfg: &ShellConfig, out: &mut String) {
    for (name, widget) in &cfg.widgets {
        match widget.widget_type.as_str() {
            "clipboard-yank" => {
                out.push_str(&format!("function {name} {{\n"));
                out.push_str("  zle vi-yank\n");
                out.push_str("  if [[ \"$(uname)\" == \"Darwin\" ]]; then\n");
                out.push_str("    echo \"$CUTBUFFER\" | pbcopy\n");
                out.push_str("  elif [[ -n \"$WAYLAND_DISPLAY\" ]]; then\n");
                out.push_str("    echo \"$CUTBUFFER\" | wl-copy\n");
                out.push_str("  elif [[ -n \"$DISPLAY\" ]]; then\n");
                out.push_str("    echo \"$CUTBUFFER\" | xsel --clipboard\n");
                out.push_str("  fi\n}\n");
                out.push_str(&format!("zle -N {name}\n"));
            }
            "fuzzy-grep" => {
                let selector = if cfg.fuzzy.backend == "skim" { "sk" } else { "fzf" };
                out.push_str(&format!("{name}() {{\n"));
                out.push_str("  local selected file line\n");
                out.push_str("  if command -v rg &> /dev/null; then\n");
                out.push_str(&format!("    selected=$(rg --color=always --line-number --no-heading --smart-case \"${{*:-}}\" 2>/dev/null | \\\n"));
                out.push_str(&format!("      {selector} --ansi --delimiter : \\\n"));
                out.push_str("        --preview 'bat --color=always --style=numbers --highlight-line {2} {1}' \\\n");
                out.push_str("        --preview-window 'up,60%,border-rounded,+{2}+3/3,~3')\n");
                out.push_str("    if [[ -n \"$selected\" ]]; then\n");
                out.push_str("      file=$(echo \"$selected\" | cut -d: -f1)\n");
                out.push_str("      line=$(echo \"$selected\" | cut -d: -f2)\n");
                out.push_str("      ${EDITOR:-vim} \"+${line}\" \"$file\"\n");
                out.push_str("    fi\n  fi\n}\n");
                out.push_str(&format!("zle -N {name}\n"));
            }
            _ => {}
        }
        if let Some(ref bind) = widget.bind {
            out.push_str(&format!("bindkey '{bind}' {name}\n"));
        }
    }
}

fn generate_aliases(cfg: &ShellConfig, out: &mut String) {
    for (group, aliases) in &cfg.aliases {
        out.push_str(&format!("# --- {group} ---\n"));
        for (name, value) in aliases {
            match value {
                AliasValue::Simple(cmd) => {
                    out.push_str(&format!("alias {name}='{cmd}'\n"));
                }
                AliasValue::Complex { command, noglob } => {
                    if *noglob {
                        out.push_str(&format!("alias {name}='noglob {command}'\n"));
                    } else {
                        out.push_str(&format!("alias {name}='{command}'\n"));
                    }
                }
            }
        }
    }
}

fn generate_starship(cfg: &ShellConfig) -> String {
    let theme = &cfg.theme;
    let green = theme.colors.get("nord14").map(|s| s.as_str()).unwrap_or("#A3BE8C");
    let red = theme.colors.get("nord11").map(|s| s.as_str()).unwrap_or("#BF616A");
    let frost = theme.colors.get("nord8").map(|s| s.as_str()).unwrap_or("#88C0D0");
    let yellow = theme.colors.get("nord13").map(|s| s.as_str()).unwrap_or("#EBCB8B");
    let orange = theme.colors.get("nord12").map(|s| s.as_str()).unwrap_or("#D08770");
    let purple = theme.colors.get("nord15").map(|s| s.as_str()).unwrap_or("#B48EAD");

    format!(
        r#"# Generated by bm-shell-engine — {theme_name} theme

format = """$hostname$directory$git_branch$git_status$nix_shell$cmd_duration
$character"""

[character]
success_symbol = "[❄](bold {green})"
error_symbol = "[❄](bold {red})"
vimcmd_symbol = "[❄](bold {green})"
vimcmd_visual_symbol = "[❄](bold {purple})"
vimcmd_replace_one_symbol = "[❄](bold {yellow})"

[git_branch]
symbol = "⎇ "
style = "bold {green}"
truncation_length = 20

[git_status]
style = "bold {yellow}"

[directory]
style = "bold {frost}"
truncate_to_repo = true
truncation_length = 3

[hostname]
style = "dimmed {frost}"
trim_at = "."

[nix_shell]
symbol = "❄ "
style = "bold {frost}"

[cmd_duration]
min_time = 2000
style = "bold {orange}"
"#,
        theme_name = cfg.theme.name,
        green = green,
        red = red,
        frost = frost,
        yellow = yellow,
        orange = orange,
        purple = purple,
    )
}

fn generate_skim_theme(_cfg: &ShellConfig) -> String {
    // Sourced by skim plugin init for standalone/blzsh mode
    "# Theme already applied via SKIM_DEFAULT_OPTIONS in zshrc\n".into()
}
